<?php
declare(strict_types=1);
/** @var FreshRSS_View $this */

$this->partial('nav_menu');

$class = '';
$state_unread = false;

if (FreshRSS_Context::userConf()->hide_read_feeds &&
	FreshRSS_Context::isStateEnabled(FreshRSS_Entry::STATE_NOT_READ) &&
	!FreshRSS_Context::isStateEnabled(FreshRSS_Entry::STATE_READ)) {
	$class = ' state_unread';
	$state_unread = true;
}
?>

<nav class="nav_menu">
	<div class="group" id="category_filter_bar">
		<a class="btn category-btn active" data-category="all">All</a>
		<?php foreach ($this->categories as $cat): ?>
			<a class="btn category-btn" data-category="cat-<?= $cat->id() ?>"><?= $cat->name() ?></a>
		<?php endforeach; ?>
	</div>
</nav>

<main id="stream" class="global<?= $class ?>">
	<h1 class="title_hidden"><?= _t('conf.reading.view.global') ?></h1>

	<?php
	$unreadArticles = 0;

	foreach ($this->categories as $cat):
		foreach ($cat->feeds() as $feed):
			$url = '?a=normal&get=f_' . $feed->id();
			$unreadArticles += $feed->nbNotRead();
	?>
			<div class="box category cat-<?= $cat->id() ?>" data-feed-id="<?= $feed->id() ?>" data-cat-id="<?= $cat->id() ?>">
				<div class="box-title">
					<h2>
						<?php if (FreshRSS_Context::userConf()->show_favicons): ?>
							<img class="favicon" src="<?= $feed->favicon() ?>" alt="" loading="lazy" style="vertical-align: middle; margin-right: 0.4em;" />
						<?php endif; ?>
						<a class="title" href="<?= $url ?>">
							<?= $feed->name() ?>
						</a>
					</h2>
				</div>
				<div class="box-content loading">Loading…</div>
			</div>
	<?php
		endforeach;
	endforeach;

	if ($unreadArticles < 1 && $state_unread): ?>
		<div id="noArticlesToShow" class="prompt alert alert-warn">
			<h2 class="alert-head"><?= _t('index.feed.empty') ?></h2>
		</div>
	<?php endif; ?>
</main>

<div id="overlay">
	<a class="close" href="#"><?= _i('close') ?></a>
	<div id="panel"<?= FreshRSS_Context::userConf()->display_posts ? '' : ' class="hide_posts"' ?>></div>
</div>
<script>
	window.context = window.context || {};
	window.context.csrf = '<?= FreshRSS_Auth::csrfToken() ?>';
</script>
