<?php

declare(strict_types=1);
/** @var FreshRSS_View $this */
$this->partial('nav_menu');

$class = '';
$state_unread = false;

if (FreshRSS_Context::userConf()->hide_read_feeds &&
	FreshRSS_Context::isStateEnabled(FreshRSS_Entry::STATE_NOT_READ) &&
	!FreshRSS_Context::isStateEnabled(FreshRSS_Entry::STATE_READ)) {
	$class = ' state_unread';
	$state_unread = true;
}
?>

<nav class="nav_menu">
	<div class="group" id="category_filter_bar">
		<a class="btn category-btn active" data-category="all">All</a>
		<?php foreach ($this->categories as $cat): ?>
			<a class="btn category-btn" data-category="cat-<?= $cat->id() ?>"><?= $cat->name() ?></a>
		<?php endforeach; ?>
	</div>
</nav>

<main id="stream" class="global<?= $class ?>">
	<h1 class="title_hidden"><?= _t('conf.reading.view.global') ?></h1>
	<?php
	$params = array_filter($_GET, 'is_string', ARRAY_FILTER_USE_KEY);
	unset($params['c'], $params['a']);
	$url_base = [
		'c' => 'index',
		'a' => 'normal',
		'params' => $params,
	];

	$unreadArticles = 0;

	foreach ($this->categories as $cat) {
		$feeds = $cat->feeds();
		if (!empty($feeds)) {
			foreach ($feeds as $feed) {
				$entries = array_slice($feed->entries(), 0, 5);
				$url_base['params']['get'] = 'f_' . $feed->id();
				$unreadArticles += $feed->nbNotRead();
	?>
				<div class="box category cat-<?= $cat->id() ?>" data-unread="<?= $feed->nbNotRead() ?>">
					<div class="box-title">
						<h2>
							<?php if (FreshRSS_Context::userConf()->show_favicons): ?>
								<img class="favicon" src="<?= $feed->favicon() ?>" alt="✇" loading="lazy" style="vertical-align: middle; margin-right: 0.4em;" />
							<?php endif; ?>
							<a class="title" href="<?= Minz_Url::display($url_base) ?>">
								<?= $feed->name() ?>
							</a>
						</h2>
					</div>
					<ul class="box-content scrollbar-thin">
						<?php foreach ($entries as $entry): ?>
							<li class="item entry">
								<a class="entry_link noAjax"
								   href="<?= htmlspecialchars($entry->link()) ?>"
								   target="_blank"
								   rel="noopener noreferrer">
								   <?= htmlspecialchars($entry->title()) ?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
	<?php
			}
		}
	}
	if ($unreadArticles < 1 && $state_unread): ?>
		<div id="noArticlesToShow" class="prompt alert alert-warn">
			<h2 class="alert-head"><?= _t('index.feed.empty') ?></h2>
		</div>
	<?php endif; ?>
</main>

<div id="overlay">
	<a class="close" href="#"><?= _i('close') ?></a>
	<div id="panel"<?= FreshRSS_Context::userConf()->display_posts ? '' : ' class="hide_posts"' ?>>
</div>
</div>
